# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171004_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='askedBy',
            field=models.CharField(max_length=50),
        ),
    ]
