# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171004_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
