# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171004_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='askedBy',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
